/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1440px",
      },
    },
    colors: {
      // Common colors
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",
      black: "var(--black)",
      white: "var(--white)",

      // CexDark:
      "cexdark-500": "var(--cexdark-500)",
      "cexdark-600": "var(--cexdark-600)",
      "cexdark-700": "var(--cexdark-700)",
      "cexdark-800": "var(--cexdark-800)",
      "cexdark-900": "var(--cexdark-900)",
      "cexdark-950": "var(--cexdark-950)",

      // Gray colors
      "gray-25": "var(--gray-25)",
      "gray-50": "var(--gray-50)",
      "gray-100": "var(--gray-100)",
      "gray-200": "var(--gray-200)",
      "gray-300": "var(--gray-300)",
      "gray-400": "var(--gray-400)",
      "gray-500": "var(--gray-500)",
      "gray-600": "var(--gray-600)",
      "gray-700": "var(--gray-700)",
      "gray-800": "var(--gray-800)",
      "gray-900": "var(--gray-900)",
      "gray-950": "var(--gray-950)",

      // Brand colors
      "brand-25": "var(--brand-25)",
      "brand-50": "var(--brand-50)",
      "brand-100": "var(--brand-100)",
      "brand-200": "var(--brand-200)",
      "brand-300": "var(--brand-300)",
      "brand-400": "var(--brand-400)",
      "brand-500": "var(--brand-500)",
      "brand-600": "var(--brand-600)",
      "brand-700": "var(--brand-700)",
      "brand-800": "var(--brand-800)",
      "brand-900": "var(--brand-900)",
      "brand-950": "var(--brand-950)",

      // Error colors
      "error-25": "var(--error-25)",
      "error-50": "var(--error-50)",
      "error-100": "var(--error-100)",
      "error-200": "var(--error-200)",
      "error-300": "var(--error-300)",
      "error-400": "var(--error-400)",
      "error-500": "var(--error-500)",
      "error-600": "var(--error-600)",
      "error-700": "var(--error-700)",
      "error-800": "var(--error-800)",
      "error-900": "var(--error-900)",
      "error-950": "var(--error-950)",

      // Warning colors
      "warning-25": "var(--warning-25)",
      "warning-50": "var(--warning-50)",
      "warning-100": "var(--warning-100)",
      "warning-200": "var(--warning-200)",
      "warning-300": "var(--warning-300)",
      "warning-400": "var(--warning-400)",
      "warning-500": "var(--warning-500)",
      "warning-600": "var(--warning-600)",
      "warning-700": "var(--warning-700)",
      "warning-800": "var(--warning-800)",
      "warning-900": "var(--warning-900)",
      "warning-950": "var(--warning-950)",

      // Success colors
      "success-25": "var(--success-25)",
      "success-50": "var(--success-50)",
      "success-100": "var(--success-100)",
      "success-200": "var(--success-200)",
      "success-300": "var(--success-300)",
      "success-400": "var(--success-400)",
      "success-500": "var(--success-500)",
      "success-600": "var(--success-600)",
      "success-700": "var(--success-700)",
      "success-800": "var(--success-800)",
      "success-900": "var(--success-900)",
      "success-950": "var(--success-950)",

      // Green colors
      "green-25": "var(--green-25)",
      "green-50": "var(--green-50)",
      "green-100": "var(--green-100)",
      "green-200": "var(--green-200)",
      "green-300": "var(--green-300)",
      "green-400": "var(--green-400)",
      "green-500": "var(--green-500)",
      "green-600": "var(--green-600)",
      "green-700": "var(--green-700)",
      "green-800": "var(--green-800)",
      "green-900": "var(--green-900)",
      "green-950": "var(--green-950)",

      // Gray blue colors
      "gray-blue-25": "var(--gray-blue-25)",
      "gray-blue-50": "var(--gray-blue-50)",
      "gray-blue-100": "var(--gray-blue-100)",
      "gray-blue-200": "var(--gray-blue-200)",
      "gray-blue-300": "var(--gray-blue-300)",
      "gray-blue-400": "var(--gray-blue-400)",
      "gray-blue-500": "var(--gray-blue-500)",
      "gray-blue-600": "var(--gray-blue-600)",
      "gray-blue-700": "var(--gray-blue-700)",
      "gray-blue-800": "var(--gray-blue-800)",
      "gray-blue-900": "var(--gray-blue-900)",
      "gray-blue-950": "var(--gray-blue-950)",

      // Blue light colors
      "blue-light-25": "var(--blue-light-25)",
      "blue-light-50": "var(--blue-light-50)",
      "blue-light-100": "var(--blue-light-100)",
      "blue-light-200": "var(--blue-light-200)",
      "blue-light-300": "var(--blue-light-300)",
      "blue-light-400": "var(--blue-light-400)",
      "blue-light-500": "var(--blue-light-500)",
      "blue-light-600": "var(--blue-light-600)",
      "blue-light-700": "var(--blue-light-700)",
      "blue-light-800": "var(--blue-light-800)",
      "blue-light-900": "var(--blue-light-900)",
      "blue-light-950": "var(--blue-light-950)",

      // Blue colors
      "blue-25": "var(--blue-25)",
      "blue-50": "var(--blue-50)",
      "blue-100": "var(--blue-100)",
      "blue-200": "var(--blue-200)",
      "blue-300": "var(--blue-300)",
      "blue-400": "var(--blue-400)",
      "blue-500": "var(--blue-500)",
      "blue-600": "var(--blue-600)",
      "blue-700": "var(--blue-700)",
      "blue-800": "var(--blue-800)",
      "blue-900": "var(--blue-900)",
      "blue-950": "var(--blue-950)",

      // Indigo colors
      "indigo-25": "var(--indigo-25)",
      "indigo-50": "var(--indigo-50)",
      "indigo-100": "var(--indigo-100)",
      "indigo-200": "var(--indigo-200)",
      "indigo-300": "var(--indigo-300)",
      "indigo-400": "var(--indigo-400)",
      "indigo-500": "var(--indigo-500)",
      "indigo-600": "var(--indigo-600)",
      "indigo-700": "var(--indigo-700)",
      "indigo-800": "var(--indigo-800)",
      "indigo-900": "var(--indigo-900)",
      "indigo-950": "var(--indigo-950)",

      // Purple colors
      "purple-25": "var(--purple-25)",
      "purple-50": "var(--purple-50)",
      "purple-100": "var(--purple-100)",
      "purple-200": "var(--purple-200)",
      "purple-300": "var(--purple-300)",
      "purple-400": "var(--purple-400)",
      "purple-500": "var(--purple-500)",
      "purple-600": "var(--purple-600)",
      "purple-700": "var(--purple-700)",
      "purple-800": "var(--purple-800)",
      "purple-900": "var(--purple-900)",
      "purple-950": "var(--purple-950)",

      // Yellow colors
      "yellow-25": "var(--yellow-25)",
      "yellow-50": "var(--yellow-50)",
      "yellow-100": "var(--yellow-100)",
      "yellow-200": "var(--yellow-200)",
      "yellow-300": "var(--yellow-300)",
      "yellow-400": "var(--yellow-400)",
      "yellow-500": "var(--yellow-500)",
      "yellow-600": "var(--yellow-600)",
      "yellow-700": "var(--yellow-700)",
      "yellow-800": "var(--yellow-800)",
      "yellow-900": "var(--yellow-900)",
      "yellow-950": "var(--yellow-950)",

      // Orange colors
      "orange-25": "var(--orange-25)",
      "orange-50": "var(--orange-50)",
      "orange-100": "var(--orange-100)",
      "orange-200": "var(--orange-200)",
      "orange-300": "var(--orange-300)",
      "orange-400": "var(--orange-400)",
      "orange-500": "var(--orange-500)",
      "orange-600": "var(--orange-600)",
      "orange-700": "var(--orange-700)",
      "orange-800": "var(--orange-800)",
      "orange-900": "var(--orange-900)",
      "orange-950": "var(--orange-950)",

      // Theme
      text: "var(--text)",
      background: "var(--background)",
      cardBg: "var(--cardBg)",
      primary: "var(--primary)",
      darkBlue: "var(--darkBlue)",
      secondaryText: "var(--secondaryText)",
      secondaryBg: "var(--secondaryBg)",
      darker: "var(--darker)",
      border: "var(--border)",
      borderDarker: "var(--borderDarker)",
      borderFaded: "var(--borderFaded)",
      grayTextPrimary: "var(--grayTextPrimary)",
      grayTextSecondary: "var(--grayTextSecondary)",
      all: "var(--all)",
      completed: "var(--completed)",
      inProgress: "var(--inProgress)",
      notStarted: "var(--notStarted)",
      bannerGradient: "var(--bannerGradient)",
      purpleText: "var(--purpleText)",
      redText: "var(--redText)",
      greenText: "var(--greenText)",
      yellowText: "var(--yellowText)",
      hoverHighlight: "var(--hoverHighlight)",
      highlightBorder: "var(--highlightBorder)",
      tableHover: "var(--tableHover)",
    },
    fontWeight: {
      regular: "var(--font-weight-regular)",
      medium: "var(--font-weight-medium)",
      semibold: "var(--font-weight-semibold)",
      bold: "var(--font-weight-bold)",
    },
    fontSize: {
      "display-2xl": [
        "var(--font-size-display-2xl)",
        {
          lineHeight: "var(--line-height-display-2xl)",
          letterSpacing: "var(--letter-spacing-display-2xl)",
        },
      ],
      "display-xl": [
        "var(--font-size-display-xl)",
        {
          lineHeight: "var(--line-height-display-xl)",
          letterSpacing: "var(--letter-spacing-display-xl)",
        },
      ],
      "display-lg": [
        "var(--font-size-display-lg)",
        {
          lineHeight: "var(--line-height-display-lg)",
          letterSpacing: "var(--letter-spacing-display-lg)",
        },
      ],
      "display-md": [
        "var(--font-size-display-md)",
        {
          lineHeight: "var(--line-height-display-md)",
          letterSpacing: "var(--letter-spacing-display-md)",
        },
      ],
      "display-sm": [
        "var(--font-size-display-sm)",
        {
          lineHeight: "var(--line-height-display-sm)",
        },
      ],
      "display-xs": [
        "var(--font-size-display-xs)",
        {
          lineHeight: "var(--line-height-display-xs)",
        },
      ],
      "text-xl": [
        "var(--font-size-text-xl)",
        {
          lineHeight: "var(--line-height-text-xl)",
        },
      ],
      "text-lg": [
        "var(--font-size-text-lg)",
        {
          lineHeight: "var(--line-height-text-lg)",
        },
      ],
      "text-md": [
        "var(--font-size-text-md)",
        {
          lineHeight: "var(--line-height-text-md)",
        },
      ],
      "text-sm": [
        "var(--font-size-text-sm)",
        {
          lineHeight: "var(--line-height-text-sm)",
        },
      ],
      "text-xs": [
        "var(--font-size-text-xs)",
        {
          lineHeight: "var(--line-height-text-xs)",
        },
      ],
    },
    fontFamily: {
      inter: ["Inter", "sans-serif"],
    },
    boxShadow: {
      xs: "var(--shadow-xs)",
      sm: "var(--shadow-sm)",
      md: "var(--shadow-md)",
      lg: "var(--shadow-lg)",
      xl: "var(--shadow-xl)",
      "2xl": "var(--shadow-2xl)",
      "3xl": "var(--shadow-3xl)",
    },
    padding: {
      0: "var(--spacing-0)",
      "1/4": "var(--spacing-0_25)",
      "1/2": "var(--spacing-0_5)",
      1: "var(--spacing-1)",
      1.5: "var(--spacing-1_5)",
      2: "var(--spacing-2)",
      3: "var(--spacing-3)",
      4: "var(--spacing-4)",
      5: "var(--spacing-5)",
      6: "var(--spacing-6)",
      7: "var(--spacing-7)",
      8: "var(--spacing-8)",
      9: "var(--spacing-9)",
      10: "var(--spacing-10)",
      11: "var(--spacing-11)",
      12: "var(--spacing-12)",
      13: "var(--spacing-13)",
      14: "var(--spacing-14)",
      15: "var(--spacing-15)",
      16: "var(--spacing-16)",
      desktop: "20px",
      mobile: "15px",
    },
    margin: {
      0: "var(--spacing-0)",
      "1/4": "var(--spacing-0_25)",
      "1/2": "var(--spacing-0_5)",
      1: "var(--spacing-1)",
      1.5: "var(--spacing-1_5)",
      2: "var(--spacing-2)",
      3: "var(--spacing-3)",
      4: "var(--spacing-4)",
      5: "var(--spacing-5)",
      6: "var(--spacing-6)",
      7: "var(--spacing-7)",
      8: "var(--spacing-8)",
      9: "var(--spacing-9)",
      10: "var(--spacing-10)",
      11: "var(--spacing-11)",
      12: "var(--spacing-12)",
      13: "var(--spacing-13)",
      14: "var(--spacing-14)",
      15: "var(--spacing-15)",
      16: "var(--spacing-16)",
      desktop: "20px",
      mobile: "15px",
      minHeight: "calc(100vh - 386px)",
    },
    gap: {
      0: "var(--spacing-0)",
      "1/4": "var(--spacing-0_25)",
      "1/2": "var(--spacing-0_5)",
      1: "var(--spacing-1)",
      1.5: "var(--spacing-1_5)",
      2: "var(--spacing-2)",
      3: "var(--spacing-3)",
      4: "var(--spacing-4)",
      5: "var(--spacing-5)",
      6: "var(--spacing-6)",
      7: "var(--spacing-7)",
      8: "var(--spacing-8)",
      9: "var(--spacing-9)",
      10: "var(--spacing-10)",
      11: "var(--spacing-11)",
      12: "var(--spacing-12)",
      13: "var(--spacing-13)",
      14: "var(--spacing-14)",
      15: "var(--spacing-15)",
      16: "var(--spacing-16)",
      desktop: "20px",
      mobile: "15px",
      minHeight: "calc(100vh - 386px)",
    },
    spacing: {
      desktop: "1440px",
      minHeight: "calc(100vh - 386px)",
    },
    borderRadius: {
      none: "var(--radius-none)",
      xs: "var(--radius-xs)",
      s: "var(--radius-s)",
      m: "var(--radius-m)",
      l: "var(--radius-l)",
      xl: "var(--radius-xl)",
      max: "var(--radius-max)",
    },
    keyframes: {
      "accordion-down": {
        from: { height: "0" },
        to: { height: "var(--radix-accordion-content-height)" },
      },
      "accordion-up": {
        from: { height: "var(--radix-accordion-content-height)" },
        to: { height: "0" },
      },
      fadeIn: {
        from: { opacity: 0 },
        to: { opacity: 1 },
      },
    },
    animation: {
      "accordion-down": "accordion-down 0.2s ease-out",
      "accordion-up": "accordion-up 0.2s ease-out",
      fade: "fadeIn .3s ease-in-out",
    },
  },
};
