export const colors = {
  text: "var(--text)",
  primary: "var(--primary)",
  darkBlue: "var(--darkBlue)",
  secondary: "var(--secondary)",
  secondaryText: "var(--secondaryText)",
  secondaryBg: "var(--secondaryBg)",
  darker: "var(--darker)",
  background: "var(--background)",
  border: "var(--border)",
  borderFaded: "var(--borderFaded)",
  grayTextPrimary: "var(--grayTextPrimary)",
  grayTextSecondary: "var(--grayTextSecondary)",
  cardBg: "var(--cardBg)",
  purpleText: "var(--purpleText)",
  redText: "var(--redText)",
  greenText: "var(--greenText)",
  yellowText: "var(--yellowText)",
} as const;
